name: 'salesforce_formula_integration_tests'
version: '0.10.0'
profile: 'integration_tests'
config-version: 2
vars:
  salesforce_formula_integration_tests:
    salesforce_schema: salesforce_formula_integrations_tests

models:
  +schema: "salesforce_formula_{{ var('directed_schema','dev') }}"

seeds:
  +docs:
    show: False
  salesforce_formula_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    opportunity:
      +columns_types:
        amount: float
        probability: float
    fivetran_formula:
      +column_types:
        view_sql: "{{ 'varchar(256)'  if target.type in ('redshift','postgres') else 'string'}}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

flags:
  send_anonymous_usage_stats: False
  use_colors: True